[workspace]
channels = ["conda-forge", "bioconda"]
name = "39-Species-Estimates"
platforms = ["linux-64"]

[environments]
default = ["main"]
r = ["r"]

[feature.main.dependencies]
python = ">=3.8"
biopython = "*"
gffutils = "*"
bcbiogff = "*"
extern = "*"
bird_tool_utils_python = "*"
snakemake = ">=8"
snakemake-executor-plugin-cluster-generic = ">=1"
polars = "*"
xlsx2csv = "*"
singlem = "*"

[feature.r.dependencies]
python = ">=3.6"
radian = "*"
r-base = "*"
r-tidyverse = "*"
r-here = "*"
r-languageserver = "*"
r-httpgd = "*"
r-cowplot = "*"
r-ggrepel = "*"
r-ggbeeswarm = "*"
r-gt = "*"
r-gtExtras = "*"
r-seqinr = "*"
r-jsonlite = "*"
r-svglite = "*"
r-webshot = "*"
r-webshot2 = "*"
r-ggalluvial = "*"
r-gggenes = "*"
r-ggextra = "*"
r-ggpubr = "*"
r-ggforce = "*"
r-ggh4x = "*"
bioconductor-complexheatmap = ">=2.1"
bioconductor-phyloseq = "*"
r-ape = "*"
r-vegan = "*"
r-ggvenndiagram = "*"
r-hrbrthemes = "*"
r-ggbreak = "*"
r-ggraph = "*"
r-propr = "*"
r-geosphere = "*" 
r-hexbin = "*"
r-tidytree = "*"
bioconductor-treeio = "*"
bioconductor-ggtree = "*"
bioconductor-ggtreeExtra = "*" 
r-emmeans = "*" 
r-maps = "*" 
r-relaimpo = "*" 
r-treemapify = "*"
r-devtools = "*"
r-ggtern = "*"

[feature.r.tasks]
install-breakaway = "R -q -e 'devtools::install_github(\"adw96/breakaway\", upgrade = \"never\")'"
